/**
 * @file apps.ts
 * @description Catalog & Metadata for all Harmony Projects mini apps.
 * Includes both core pre-installed apps and central repository downloadable packages.
 */

import { MiniAppConfig } from '../types';
import { getLucideCdnIconUrl } from '../lib/cdn';

export const HARMONY_APPS: MiniAppConfig[] = [
  {
    id: 'harmony-notes',
    name: 'Harmony Notes',
    tagline: 'Smart Notes & Category Organizers',
    iconName: 'notebook',
    iconCdnUrl: getLucideCdnIconUrl('notebook'),
    colorGradient: 'from-amber-400 via-orange-500 to-amber-600',
    bgHex: '#f59e0b',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-notes/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-notes',
    description: 'Capture quick thoughts, bullet points, voice memos, and tagged categories.',
    badge: 'Notes',
    version: '2.1.0',
    size: '1.2 MB',
    author: 'Harmony Core',
    category: 'productivity',
    isSystemApp: true,
    rating: 4.9
  },
  {
    id: 'harmony-docs',
    name: 'Harmony Docs',
    tagline: 'Rich Text Workspace & Documents',
    iconName: 'file-text',
    iconCdnUrl: getLucideCdnIconUrl('file-text'),
    colorGradient: 'from-blue-500 via-indigo-500 to-cyan-600',
    bgHex: '#3b82f6',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-docs/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-docs',
    description: 'Collaborative document editing, word counting, formatting, and exported PDFs.',
    badge: 'Docs',
    version: '2.3.4',
    size: '2.4 MB',
    author: 'Harmony Core',
    category: 'productivity',
    isSystemApp: true,
    rating: 4.9
  },
  {
    id: 'harmony-writing',
    name: 'Harmony Writing',
    tagline: 'Focus Studio & Daily Word Target',
    iconName: 'pen-tool',
    iconCdnUrl: getLucideCdnIconUrl('pen-tool'),
    colorGradient: 'from-emerald-400 via-teal-500 to-emerald-600',
    bgHex: '#10b981',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-writing/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-writing',
    description: 'Distraction-free typewriter environment, soundscapes, ambient timers, and stats.',
    badge: 'Studio',
    version: '1.8.0',
    size: '1.8 MB',
    author: 'Harmony Core',
    category: 'productivity',
    isSystemApp: true,
    rating: 4.8
  },
  {
    id: 'harmony-music-player',
    name: 'Harmony Music',
    tagline: 'Hi-Fi Playlists & Audio Synth',
    iconName: 'disc',
    iconCdnUrl: getLucideCdnIconUrl('disc'),
    colorGradient: 'from-fuchsia-500 via-purple-600 to-pink-500',
    bgHex: '#d946ef',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-music-player/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-music-player',
    description: 'iOS style Music Player with ambient streams, custom playlists, equalizer, and background mode.',
    badge: 'Audio',
    version: '3.0.1',
    size: '3.1 MB',
    author: 'Harmony Sound Team',
    category: 'audio',
    isSystemApp: true,
    rating: 5.0
  },
  {
    id: 'harmony-docs-ai',
    name: 'Harmony Docs AI',
    tagline: 'Gemini Document Intelligence & Copilot',
    iconName: 'sparkles',
    iconCdnUrl: getLucideCdnIconUrl('sparkles'),
    colorGradient: 'from-violet-500 via-purple-600 to-indigo-700',
    bgHex: '#8b5cf6',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-docs-ai/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-docs-ai',
    description: 'Ask questions, summarize long documents, generate outlines, and refine draft prose.',
    badge: 'AI',
    version: '2.0.0',
    size: '1.9 MB',
    author: 'Harmony AI Lab',
    category: 'ai',
    isSystemApp: true,
    rating: 4.9
  },
  {
    id: 'harmony-calendar',
    name: 'Harmony Calendar',
    tagline: 'Gregorian • Hijri • Ethiopian with Google Sync',
    iconName: 'calendar',
    iconCdnUrl: getLucideCdnIconUrl('calendar'),
    colorGradient: 'from-rose-500 via-red-600 to-amber-600',
    bgHex: '#ef4444',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-calendar/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-calendar',
    description: 'Tri-calendar system supporting Gregorian, Hijri, and Ethiopian dates, live converter, and Google Calendar sync.',
    badge: 'Calendar',
    version: '2.2.0',
    size: '1.6 MB',
    author: 'Harmony Core',
    category: 'productivity',
    isSystemApp: true,
    rating: 4.9
  },
  {
    id: 'harmony-finance',
    name: 'Harmony Finance',
    tagline: 'Expense Ledger, Budgets & Loan EMI Amortization',
    iconName: 'wallet',
    iconCdnUrl: getLucideCdnIconUrl('wallet'),
    colorGradient: 'from-emerald-500 via-teal-600 to-cyan-700',
    bgHex: '#059669',
    deployedUrl: 'https://abduedris313-max.github.io/harmony-finance/',
    repoUrl: 'https://github.com/abduedris313-max/harmony-finance',
    description: 'Personal finance & wealth engine: cash flow ledger, category budgets, debt amortization schedules, and Gemini AI advisor.',
    badge: 'Finance',
    version: '2.5.0',
    size: '2.8 MB',
    author: 'Harmony Finance Group',
    category: 'finance',
    isSystemApp: true,
    rating: 4.9
  },
  {
    id: 'harmony-app-store',
    name: 'App Store',
    tagline: 'Central Repository & Ecosystem App Hub',
    iconName: 'shopping-bag',
    iconCdnUrl: getLucideCdnIconUrl('shopping-bag'),
    colorGradient: 'from-blue-600 via-sky-500 to-indigo-600',
    bgHex: '#0284c7',
    deployedUrl: '#',
    repoUrl: 'https://github.com/abduedris313-max/harmony-super-app',
    description: 'Harmony ecosystem central repository: fetch packages, stream download, and install mini-apps with offline persistence.',
    badge: 'Store',
    version: '2.4.0',
    size: '1.4 MB',
    author: 'Harmony Core Systems',
    category: 'utilities',
    isSystemApp: true,
    rating: 5.0
  },
  // Downloadable Packages from Central Repository
  {
    id: 'harmony-weather',
    name: 'Weather & Sky',
    tagline: 'Atmospheric Forecast & Multi-City Metrics',
    iconName: 'cloud-sun',
    iconCdnUrl: getLucideCdnIconUrl('cloud-sun'),
    colorGradient: 'from-sky-400 via-blue-500 to-indigo-600',
    bgHex: '#0ea5e9',
    deployedUrl: '#',
    repoUrl: 'https://github.com/abduedris313-max/harmony-weather',
    description: 'Real-time weather radar, 24-hour temperatures, UV Index, air quality metrics, and international city weather tracking.',
    badge: 'Weather',
    version: '1.2.0',
    size: '1.7 MB',
    author: 'Atmosphere Labs',
    category: 'utilities',
    isSystemApp: false,
    rating: 4.9
  },
  {
    id: 'harmony-calculator',
    name: 'Calculator & Units',
    tagline: 'Scientific Engine & Multi-Unit Converter',
    iconName: 'calculator',
    iconCdnUrl: getLucideCdnIconUrl('calculator'),
    colorGradient: 'from-amber-500 via-orange-600 to-red-500',
    bgHex: '#f97316',
    deployedUrl: '#',
    repoUrl: 'https://github.com/abduedris313-max/harmony-calculator',
    description: 'Standard and scientific mathematical calculation engine with tape history and currency, length, and temperature converters.',
    badge: 'Tool',
    version: '1.5.0',
    size: '1.1 MB',
    author: 'Numerics Studio',
    category: 'utilities',
    isSystemApp: false,
    rating: 4.8
  },
  {
    id: 'harmony-focus',
    name: 'Focus Studio',
    tagline: 'Pomodoro Timer & 432Hz Sound Synthesizer',
    iconName: 'clock',
    iconCdnUrl: getLucideCdnIconUrl('clock'),
    colorGradient: 'from-rose-500 via-pink-600 to-purple-600',
    bgHex: '#e11d48',
    deployedUrl: '#',
    repoUrl: 'https://github.com/abduedris313-max/harmony-focus',
    description: 'Interval productivity timer with circular SVG progress rings, 432Hz binaural audio synthesizer, and session streak tracker.',
    badge: 'Focus',
    version: '2.0.1',
    size: '2.2 MB',
    author: 'Zenith Labs',
    category: 'productivity',
    isSystemApp: false,
    rating: 4.9
  },
  {
    id: 'harmony-terminal',
    name: 'Dev Terminal',
    tagline: 'System Diagnostics & Package Manager CLI',
    iconName: 'terminal',
    iconCdnUrl: getLucideCdnIconUrl('terminal'),
    colorGradient: 'from-emerald-500 via-teal-600 to-slate-800',
    bgHex: '#0f766e',
    deployedUrl: '#',
    repoUrl: 'https://github.com/abduedris313-max/harmony-terminal',
    description: 'Interactive command shell for inspecting service worker caches, repository ping diagnostics, and package management.',
    badge: 'Dev',
    version: '1.1.0',
    size: '1.3 MB',
    author: 'Harmony DevTools',
    category: 'developer',
    isSystemApp: false,
    rating: 4.7
  },
  {
    id: 'harmony-habits',
    name: 'Habit Momentum',
    tagline: 'Concentric Activity Rings & Daily Goals',
    iconName: 'activity',
    iconCdnUrl: getLucideCdnIconUrl('activity'),
    colorGradient: 'from-cyan-500 via-teal-500 to-emerald-600',
    bgHex: '#06b6d4',
    deployedUrl: '#',
    repoUrl: 'https://github.com/abduedris313-max/harmony-habits',
    description: 'Apple Health-inspired habit tracking with concentric SVG activity rings, daily streak counter, and haptic feedback.',
    badge: 'Habits',
    version: '1.0.4',
    size: '1.8 MB',
    author: 'Momentum Health',
    category: 'health',
    isSystemApp: false,
    rating: 4.9
  }
];
